# Generated by Django 5.0.7 on 2024-08-21 12:16

from django.db import migrations

def populate_resources(apps, schema_editor):
    Resources = apps.get_model('main', 'Resource')
    resources = [
        "Water",
        "Air",
        "Earth"
    ]
    for resource_name in resources:
        Resources.objects.create(name=resource_name)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resource_spaceobject'),
    ]

    operations = [
        migrations.RunPython(populate_resources),
    ]
