# Generated by Django 5.0.7 on 2024-08-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240821_1216'),
    ]

    operations = [
    ]
