# Generated by Django 5.0.7 on 2024-08-21 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userresources'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceObjectPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_object_prices', to='main.resource')),
                ('spaceObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_object_prices', to='main.spaceobject')),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spaceObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='main.spaceobject')),
            ],
        ),
    ]
