# Generated by Django 5.0.7 on 2024-08-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_spaceobjectprice_storeitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreItem',
        ),
    ]
