# Generated by Django 5.0.7 on 2024-08-21 16:30

from django.db import migrations

def reverse_populate_space_objects(apps, schema_editor):
    SpaceObject = apps.get_model('main', 'SpaceObject')
    spaceObjects = [
        {
            "WaterWorld",
            "WaterWorld_clouds",
            "WaterWorld_land",
            "WaterWorld_clouds_land"
        },
    ]
    for space_object_name in spaceObjects:
        SpaceObject.objects.filter(name=space_object_name).delete()
        

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20240821_1624'),
    ]

    operations = [
        migrations.RunPython(reverse_populate_space_objects),
    ]
