# Generated by Django 5.0.7 on 2024-08-21 16:35

from django.db import migrations

def reverse_populate_space_objects(apps, schema_editor):
    SpaceObject = apps.get_model('main', 'SpaceObject')
    space_object_name = "{'WaterWorld_clouds', 'WaterWorld_clouds_land', 'WaterWorld', 'WaterWorld_land'}"
    SpaceObject.objects.filter(name=space_object_name).delete()

        

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20240821_1630'),
    ]

    operations = [
        migrations.RunPython(reverse_populate_space_objects),
    ]
