# Generated by Django 5.0.7 on 2024-08-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_populating_1st_planets'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceobject',
            name='image_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
