# Generated by Django 5.0.7 on 2024-09-02 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_spaceobject_image_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceobjectprice',
            name='description',
            field=models.TextField(default='???'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spaceobjectprice',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_object_prices_resources', to='main.resource'),
        ),
        migrations.AlterField(
            model_name='spaceobjectprice',
            name='spaceObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_object_prices_space_objects', to='main.spaceobject'),
        ),
        migrations.AlterField(
            model_name='userresources',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resources_resources', to='main.resource'),
        ),
        migrations.AlterField(
            model_name='userresources',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resources_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResourceTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outputQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inputResource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_transformations', to='main.resource')),
                ('outputResource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_transformations', to='main.resource')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceObjectGenerates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_object_generates_resources', to='main.resource')),
                ('spaceObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_object_generates_space_objects', to='main.spaceobject')),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgradeDescription', models.TextField(default='???', null=True)),
                ('baseSpaceObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_upgrades', to='main.spaceobject')),
                ('upgradedSpaceObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgraded_upgrades', to='main.spaceobject')),
            ],
        ),
        migrations.CreateModel(
            name='UpgradeCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_costs_resources', to='main.resource')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_costs_upgrades', to='main.upgrade')),
            ],
        ),
        migrations.CreateModel(
            name='UserGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('spaceObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_grids_space_objects', to='main.spaceobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_grids_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
