# Generated by Django 5.0.7 on 2024-09-02 15:09

from django.db import migrations

def populate_space_objects(apps, schema_editor):
    SpaceObjects = apps.get_model('main', 'SpaceObject')
    space_objects = [
        {
        "name": "Water World",
        "description": "A simple planet covered in water.",
        "image_path": "images/Planets/WaterWorld.svg"
        }
    ]
    for obj in space_objects:
        SpaceObjects.objects.create(name=obj["name"], description=obj["description"], image_path=obj["image_path"])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_spaceobjectprice_description_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_space_objects),
    ]
