# Generated by Django 5.0.7 on 2024-09-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_adding_elementary_matter'),
    ]

    operations = [
    ]
