# Generated by Django 5.0.7 on 2024-09-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_test_SO_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceobjectprice',
            name='description',
        ),
    ]
