# Generated by Django 5.0.7 on 2024-09-02 16:50

from django.db import migrations
# Generated by Django 5.0.7 on 2024-09-02 16:31

def create_space_object_price(apps, schema_editor):
    SpaceObjectPrice = apps.get_model('main', 'SpaceObjectPrice')

    print("Creating SpaceObjectPrice entries...")

    SpaceObjectPrice.objects.create(spaceObject_id=1, resource_id=4, quantity=100)
    SpaceObjectPrice.objects.create(spaceObject_id=1, resource_id=1, quantity=240)

    print("SpaceObjectPrice entries created.")

    
class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_test_SO_price'),
    ]

    operations = [
    ]
