# Generated by Django 5.0.7 on 2024-09-04 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_removing_redundant_SO_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpaceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spaceObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_space_objects', to='main.spaceobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_space_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
