# Generated by Django 5.0.7 on 2024-09-05 12:45

from django.db import migrations
def populate_userSpaceObjects(apps, schema_editor):
    userSpaceObject = apps.get_model('main', 'UserSpaceObject')
    
    userSpaceObject.objects.create(user_id=3, spaceObject_id=1, quantity=1)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_userspaceobject'),
    ]

    operations = [
        migrations.RunPython(populate_userSpaceObjects)
    ]
