# Generated by Django 5.0.7 on 2024-10-07 13:20

from django.db import migrations

def populatre_user_resources(apps, schema_editor):
    UserReources = apps.get_model('main', 'UserResources')
    UserReources.objects.create(user_id=3, resource_id=4, quantity=600)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_populating_resources'),
    ]

    operations = [
            migrations.RunPython(populatre_user_resources)
    ]

