# Generated by Django 5.0.7 on 2024-10-07 17:33

from django.db import migrations

def update_resource_name(apps, schema_editor):
    Resource = apps.get_model('main', 'Resource')
    Resource.objects.filter(id=4).update(name='Prime Matter')



def populatre_user_resources(apps, schema_editor):
    UserResources = apps.get_model('main', 'UserResources')
    UserResources.objects.create(user_id=3, resource_id=1, quantity=1200)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_populating_user_resources_for_testing'),
    ]

    operations = [
        migrations.RunPython(populatre_user_resources),
        migrations.RunPython(update_resource_name)
    ]
