# Generated by Django 5.0.7 on 2024-10-10 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_update_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrid',
            name='last_collected',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
