# Generated by Django 5.0.7 on 2024-10-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_usergrid_last_collected'),
    ]

    operations = [
    ]
