# Generated by Django 5.0.7 on 2024-10-17 14:27

from django.db import migrations


def populate_space_object_generates(apps, schema_editor):
    SpaceObjectGenerates = apps.get_model('main', "SpaceObjectGenerates")

    print("Creating SpaceObjectPrice entries...")

    SpaceObjectGenerates.objects.create(spaceObject_id=1, resource_id=1, quantity=10)

    print("SpaceObjectPrice entries created.")
    

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_populating_spaceObject_generates'),
    ]

    operations = [
        migrations.RunPython(populate_space_object_generates)
    ]
