# Generated by Django 5.0.7 on 2024-10-24 17:31

from django.db import migrations
def adding_quantity_to_prime_matter(apps, schema_editor):
    userResources = apps.get_model("main", "UserResources")
    userResources.objects.filter(id=1).update(quantity=3000)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_populating_spaceObject_generates2'),
    ]

    operations = [
        migrations.RunPython(adding_quantity_to_prime_matter)
    ]
