# Generated by Django 5.0.7 on 2024-10-25 12:58

from django.db import migrations
def populate_test_resource_transformation(apps, schema_editor):
    resourceTransformation = apps.get_model('main', 'ResourceTransformation')
    resourceTransformation.objects.create(inputResource_id=1, outputResource_id=4, inputQuantity=10, outputQuantity=1)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_adding_quantity_to_prime_matter_123user'),
    ]

    operations = [
        migrations.RunPython(populate_test_resource_transformation)
    ]