# Generated by Django 5.0.7 on 2024-10-27 14:24

from django.db import migrations
def populate_space_objects(apps, schema_editor):
    spaceObjects = apps.get_model('main', 'SpaceObject')
    space_objects = [
        {
            "name": "Air World",
            "description": "A giant made out of gas.",
            "image_path": "images/AirWorld.svg"
        },
        {
            "name": "Earth World",
            "description": "A world covered in Dirt, soil and some flora.",
            "image_path": "images/Planets/DesertPlanet.svg"
        },
        {
            "name": "Sun",
            "description": "Ancient human civilizations named their planet's star, believing it to be a god.",
            "image_path": "images/Planets/Sun.svg"
        },
        {
            "name": "Air World Electrified",
            "description": "A gas giant covered in never ending, violent storms.",
            "image_path": "images/Planets/AirWorld_energy.svg"
        },
    ]
    for obj in space_objects:
        spaceObjects.objects.create(name=obj["name"], description=obj["description"], image_path=obj["image_path"])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_populating_for_test_resource_tranformation'),
    ]

    operations = [
        migrations.RunPython(populate_space_objects)
    ]
