# Generated by Django 5.0.7 on 2024-10-27 14:54

from django.db import migrations
def populate_store(apps, schema_editor):
    SpaceObjectPrice = apps.get_model('main', 'SpaceObjectPrice')

    SpaceObjectPrice.objects.create(spaceObject_id=2, resource_id=2, quantity = 200)
    SpaceObjectPrice.objects.create(spaceObject_id=3, resource_id=3, quantity = 200)
    SpaceObjectPrice.objects.create(spaceObject_id=4, resource_id=5, quantity = 200)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_populating_space_objects'),
    ]

    operations = [
    ]
