# Generated by Django 5.0.7 on 2024-10-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_populating_store_fix2'),
    ]

    operations = [
    ]
