# Generated by Django 5.0.7 on 2024-10-27 16:44

from django.db import migrations
def populate_resource_transformatons(apps, schema_editor):
    resourceTransformations = apps.get_model('main', 'ResourceTransformation')
    transformation = resourceTransformations.objects.filter(
        inputResource_id=2, 
        outputResource_id=4, 
        inputQuantity=10, 
        outputQuantity=1
    ).first()
    if transformation:
        transformation.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_populating_resource_transformatons'),
    ]

    operations = [
        migrations.RunPython(populate_resource_transformatons)
    ]
