# Generated by Django 5.0.7 on 2024-10-27 19:05

from django.db import migrations, models

def delete_duplicates(apps, schema_editor):
    ResourceTransformation = apps.get_model('main', 'ResourceTransformation')
    
    # Identify duplicates based on the fields that should be unique
    duplicates = ResourceTransformation.objects.values(
        'inputResource_id', 'outputResource_id', 'inputQuantity', 'outputQuantity'
    ).annotate(
        count=models.Count('id')
    ).filter(count__gt=1)
    
    # Loop through the duplicates and delete all but one
    for duplicate in duplicates:
        transformations = ResourceTransformation.objects.filter(
            inputResource_id=duplicate['inputResource_id'],
            outputResource_id=duplicate['outputResource_id'],
            inputQuantity=duplicate['inputQuantity'],
            outputQuantity=duplicate['outputQuantity']
        )
        # Keep the first entry and delete the rest
        transformations.exclude(id=transformations.first().id).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_previous_migration'),  # Update this to your actual previous migration
    ]

    operations = [
        migrations.RunPython(delete_duplicates),
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_populating_resource_transformatons'),
    ]

    operations = [
    ]
