# Generated by Django 5.0.7 on 2024-10-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_delete_trash_from_transofmrations'),
    ]

    operations = [
    ]
