# Generated by Django 5.0.7 on 2024-10-30 16:41

from django.db import migrations
def populate(apps, schema_editor):
    SpaceObject = apps.get_model('main', 'SpaceObject')
    SpaceObject.objects.create(name="Water World Air", image_path="images/Planets/WaterWorld_Air.svg", description="A cloudy planet covered in water")
    SpaceObject.objects.create(name="Water World Earth", image_path="images/Planets/WaterWorld_Earth.svg", description="A simple planet covered in water and soil")
    SpaceObject.objects.create(name="Water World Earth Air", image_path="images/Planets/WaterWorld_Earth_Air.svg", description="A cloudy world, covered in water and soil. Could hold life")

    
class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_populating_space_objects_generates_for_earth_air_sun'),
    ]

    operations = [
        migrations.RunPython(populate),
    ]
