# Generated by Django 5.0.7 on 2024-10-30 16:54

from django.db import migrations
def populate(apps, schema_editor):
    Upgrade = apps.get_model('main', 'Upgrade')

    Upgrade.objects.create(baseSpaceObject_id=1, upgradedSpaceObject_id=6, upgradeDescription="Add air to the Water World")
    Upgrade.objects.create(baseSpaceObject_id=1, upgradedSpaceObject_id=7, upgradeDescription="Add earth to the Water World")

    Upgrade.objects.create(baseSpaceObject_id=6, upgradedSpaceObject_id=8, upgradeDescription="Add Earth to a cloudy Water World")
    Upgrade.objects.create(baseSpaceObject_id=7, upgradedSpaceObject_id=8, upgradeDescription="Add Air to the Earthly Water World")

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_populating_spaceobjects'),
    ]

    operations = [
        migrations.RunPython(populate),
    ]
