# Generated by Django 5.0.7 on 2024-11-06 13:40

from django.db import migrations
def populate(apps, schema_editor):
    upgradecost = apps.get_model('main', 'UpgradeCost')
    # add air to water world
    upgradecost.objects.create(upgrade_id=1, resource_id=2, quantity=250) 
     # add earth to water world
    upgradecost.objects.create(upgrade_id=2, resource_id=3, quantity=250) 
     # add earth to cloudy water world
    upgradecost.objects.create(upgrade_id=3, resource_id=3, quantity=300) 
     # add air to earthly water world
    upgradecost.objects.create(upgrade_id=4, resource_id=2, quantity=300) 

def change_water_world_price(apps, schema_editor):
    spaceObjectsPrice = apps.get_model('main', 'SpaceObjectPrice')
    spaceObjectsPrice.objects.filter(spaceObject_id=1).all().delete()
    spaceObjectsPrice.objects.create(spaceObject_id=1, resource_id=1, quantity=200)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_populating_upgrades'),
    ]

    operations = [
        migrations.RunPython(populate),
        migrations.RunPython(change_water_world_price)
    ]
